### ISSUE TITLE
IC flash W25Q16DVSSIG TR

### ISSUE THREAD

**Issue by yaakovgamliel** [greatscottgadgets/greatfet-hardware#1]
Hi, looks like this memory its not longer in production, I've found diferent ones with the same specs, Do you know anything about it?

**Comment by dominicgs** [comment]
We have been experimenting with alternative parts.  We have had success with the W25Q16JVSSIQ, but I don't know if we have definitely settled on that part yet.

**Comment by mossmann** [comment]
Yes, we've settled on that part.
Fixed in 8064466310b720e6ca861558e24e03762510778a.
