### ISSUE TITLE
Non-GSG neighbor naming

### ISSUE THREAD

**Issue by AsFaBw** [greatscottgadgets/greatfet-hardware#16]
Dear GSG-Team,

I have started to build a neighbor ( https://github.com/AsFaBw/greatfet-erica ) and called the neighbor GreatFET-Erica. 

Meanhwhile I am not sure anymore, if the "GreatFET" may be used for non Great Scott Gadgets neighbors. On one hand "GreatFET" was within the template. On the other hand "GreatFET" is a registered trademark according to https://greatscottgadgets.com/trademarks/ .

What is the advise for the "GreatFET" trademark within non GSG neighbors projects?

Further there is the "https://greatscottgadgets.com" text within the template. What about non-GSG neighbors? I changed it to "for GreatFET One have a look to https://greatscottgadgets.com" ? Is that in line with GSG expectations?

Best regards & thanks,
Thomas

**Comment by mossmann** [comment]
I posted some guidelines for you (and others): https://github.com/greatscottgadgets/greatfet/wiki/Board-Naming

This repo is deprecated and will be removed soon.  Please use the [GreatFET issues list](https://github.com/greatscottgadgets/greatfet/issues) for general GreatFET issues.
