### ISSUE TITLE
where is the pc software for greatfet

### ISSUE THREAD

**Issue by wanming2008** [greatscottgadgets/greatfet-hardware#2]
hi   mossmann and dominicgs

  i have made one greatfet hardware  myself but i can not find the pc software in github，in greatfet repository  or dominicgs“ framware repository。  i tried  usb goodfet PC python software whrited by  travisgoodspeed，but it seems not work。PC can not comincation with greatfet。 can you tell me where i can download the pc python software for greatfet。 

 and wish to see your speech in blackhat USA  2017 
 LOL

**Comment by dominicgs** [comment]
I answered this issue on the GreatFET_experimental repository.
